version: '3'
services:
  server:
    build:
      context: ./server
    ports:
      - "8080:8080"
    container_name: server
    volumes:
       - ./server:/usr/src/app/server
       - /usr/src/app/server/node_modules
  frontend:
    build:
      context: ./frontend
    ports:
      - "3001:3000"
    container_name: frontend
    # to start with an interactive mode
    stdin_open: true
    volumes:
       - ./frontend:/usr/src/app/frontend
       - /usr/src/app/frontend/node_modules